### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by cadedopp** [lastmjs/educell-website#14]
trying to setup google analytics on the website. Looks like we can either add a tracking id to the content management system (I don't think we have that), or add some code to the header. I looked at the header on github and am not sure where to stick the code. Ideally it would go in the header on every page, but I don't know if it will work with the popup style pages we have, so maybe we just put it in the header for the index...?

Here's the code. Should go "right before the closing </head> tag"

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125080982-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125080982-1');
</script>

**Comment by lastmjs** [comment]
It's not so simple as to just throw up Google Analytics. We need to have a
privacy policy up now per Google's terms, which requires crafting one and
putting it into the site. Do we really need Google Analytics?

**Comment by lastmjs** [comment]
I think it's a nice to have that's not really necessary right now. But if
you want it, please read the Google Analytics terms, and come up with the
list of requirements for our Terms of Use and Privacy Policy. There
shouldn't be too much, but they do have requirements we need to comply
with. Actually integrating Google Analytics after that is simple

**Comment by cadedopp** [comment]
Gotcha. We're running adds now, so the the analytics are important to track add performance. We're getting $10,000/ month to use on adds so I think it would be good to take advantage of that. It would also be nice if the adds work and we don't have to spend time doing sales.

I'll get the privacy policy written up.

**Comment by cadedopp** [comment]
Can we use this?
https://github.com/insites/cookieconsent
And it looks like this is what we need to link to:
https://policies.google.com/technologies/partner-sites

I'll add it to our footer.

**Comment by lastmjs** [comment]
Maybe we can talk about this in person, but I strongly believe the ads will
be ineffective and there's no way they will replace reaching out in person.
We're not trying to reach consumers, we're really more of a business to
business. We have to reach out individually to influencers.

The cookie consent thing is slightly different, we should just write
everything up in terms or privacy policy as necessary. That specific cookie
thing is for some European laws U believe, which will probably be
applicable but is separate from Google's requirements last I checked

**Comment by cadedopp** [comment]
I messed up the code on the googleanalytics pull request so I closed it and just updated the background pull request with the privacy policy in the footer.
